# Podcast dataset path
dataset_path: /unix/cdtdisspotify/data/spotify-podcasts-2020/

# Path to list of podcast episode uri's to extract features from
uri_path: ./data/uri_list_2.txt

# Output location for extracted features. This should just be the base output location
# as the extraction code creates feature specific folders within this directory (e.g. opensmile)
output_path: ./features

# Number of worker threads to use for feature extraction
num_workers: 8