data_audio: /unix/cdtdisspotify/data/spotify-podcasts-2020/podcasts-audio/
data_transcripts: /unix/cdtdisspotify/data/spotify-podcasts-2020/podcasts-transcripts
uri_path: ./data/uri_list2.txt
output_path: ./features
opensmile_config: ./data/custom_FrameModeFunctionals.conf.inc
num_workers: 5