name: contrastive

data_name: podcasts
data_method: sequential
data_sample_length: 1
data_shuffle_buffer: 1000
data_path: /mnt/storage/cdtdisspotify/raw/
data_feature: log_mel
data_positive_noise: 0.001
data_batch_size: 128

#data_name: crema_d
#data_sr: 16000
#data_method: sequential
#data_sample_length: 1
#data_shuffle_buffer: 1000
#data_feature: log_mel
#data_split: train
#data_positive_noise: 0.001
#data_batch_size: 64

model_embedding_dim: 512
model_temperature: 0.2
model_pooling_type: max
model_similarity_type: bilinear
model_learning_rate: 0.001

train_epochs: 20
train_steps_per_epoch: 20