name: finetune

data_name: crema_d
data_sr: 16000
data_sample_length: 1
data_shuffle_buffer: 1000
data_feature: log_mel
data_train_split: train
data_test_split: test
data_batch_size: 64

load_pretrained: True
pretrained_path: None
pretrained_ckpt: ckpt_20

contrastive_embedding_dim: 512
contrastive_temperature: 0.2
contrastive_pooling_type: max
contrastive_similarity_type: bilinear
learning_rate: 0.001

freeze_encoder: False
epochs: 50
