name: supervised

data_name: crema_d
data_sr: 16000
data_sample_length: 1
data_shuffle_buffer: 1000
data_feature: log_mel
data_train_split: train
data_test_split: test
data_batch_size: 64

load_pretrained: False
contrastive_pooling_type: max
freeze_encoder: False
learning_rate: 0.001
epochs: 50

